
stat-server.url: http://localhost:9090

server:
  port: 8080

spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
        generate-ddl: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6543/ewm
    username: ewm_user
    password: ewmpass

  sql.init:
    mode: always
    schema-locations: classpath:schema.sql

logging.level:
  org:
    springframework.orm.jpa: INFO
    springframework.transaction: INFO
    springframework.transaction.interceptor: TRACE
    springframework.orm.jpa.JpaTransactionManager: DEBUG
  ru.practicum.explore-with-me: INFO

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm
    username: test
    password: test
  config:
    activate:
      on-profile: test