spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
        generate-ddl: false

  sql.init:
    mode: always
    schema-locations: classpath:schema.sql

logging.level:
  org:
    springframework.orm.jpa: INFO
    springframework.transaction: INFO
    springframework.transaction.interceptor: TRACE
    springframework.orm.jpa.JpaTransactionManager: DEBUG
  ru.practicum.explore-with-me: INFO

server:
  port: 9090

---
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/stat
    username: stat_user
    password: statpass

---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:stat
    username: test
    password: test
  config:
    activate:
      on-profile: ci,test