CREATE TABLE IF NOT EXISTS endpoint_hits
(
    endpoint_hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app             VARCHAR(255)                            NOT NULL,
    uri             VARCHAR(512)                            NOT NULL,
    ip              VARCHAR(16)                             NOT NULL,
    timestamp       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_endpoint_hit PRIMARY KEY (endpoint_hit_id)
);